#!/usr/bin/env sh
# Nginx entrypoint. Works as root (legacy) AND as any non-root UID/GID
# (Swarm `user: "3001:3001"`). Config is rendered at start-up into NGINX_RUN_DIR
# (writable by anyone) and can be overridden from /overrides.
set -eu

TEMPLATE_DIR="${TEMPLATE_DIR:-/usr/local/share/nginx-templates}"
NGINX_RUN_DIR="${NGINX_RUN_DIR:-/tmp/nginx}"
NGINX_CONF_DIR="${NGINX_CONF_DIR:-/etc/nginx}"
OVERRIDES_DIR="${OVERRIDES_DIR:-/overrides}"
WEBSITE_ROOT="${WEBSITE_ROOT:-/home/www-data/website}"
BROTLI_MODULE_DIR="${BROTLI_MODULE_DIR:-/usr/lib/nginx/modules}"
LEGACY_CUSTOM="${LEGACY_CUSTOM:-/etc/nginx/sites-available/website.custom}"

# ---------- Settings (all overridable with env vars) ----------
PUBLIC_DIR="${PUBLIC_DIR:-public}"
LISTEN_PORT="${LISTEN_PORT:-80}"
MODE="${MODE:-php}"                       # php | static
PHP_MODE="${PHP_MODE:-classic}"           # classic | front
PHP_FRONT_SCRIPT="${PHP_FRONT_SCRIPT:-index.php}"   # main entry point (internal in front mode)
PHP_ALLOWED_SCRIPTS="${PHP_ALLOWED_SCRIPTS:-}"      # front mode: other scripts reachable by URL (comma separated)
PHP_ALLOWED_SCRIPTS_IPS="${PHP_ALLOWED_SCRIPTS_IPS:-}"  # front mode: restrict those scripts to these IPs/CIDRs
ERROR_PAGES="${ERROR_PAGES:-on}"                    # on | off: styled pages for errors generated by nginx
ERROR_LANG="${ERROR_LANG:-fr}"                      # fr | en: language of the default error pages
INTERCEPT_PHP_ERRORS="${INTERCEPT_PHP_ERRORS:-off}" # on: also replace error pages returned by PHP
HTTPS="${HTTPS:-on}"                      # on | off | auto
FASTCGI_PASS="${FASTCGI_PASS:-php:9900}"
FASTCGI_READ_TIMEOUT="${FASTCGI_READ_TIMEOUT:-300s}"
CLIENT_MAX_BODY_SIZE="${CLIENT_MAX_BODY_SIZE:-64M}"
CACHE_STATIC_MAX_AGE="${CACHE_STATIC_MAX_AGE:-3600}"
CORS_ALLOW_ORIGIN="${CORS_ALLOW_ORIGIN-*}"
X_FRAME_OPTIONS="${X_FRAME_OPTIONS-DENY}"
REAL_IP_FROM="${REAL_IP_FROM-10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}"
WORKER_PROCESSES="${WORKER_PROCESSES:-auto}"
ERROR_LOG_LEVEL="${ERROR_LOG_LEVEL:-warn}"
ACCESS_LOG_ENABLED="${ACCESS_LOG_ENABLED:-1}"
BROTLI="${BROTLI:-auto}"                  # auto | on | off

# ---------- Backward compatibility with previous variables ----------
[ "${ALONE:-false}" = "true" ] && MODE="static"
[ -n "${FASTCGI_PASS_VALUE:-}" ] && FASTCGI_PASS="$FASTCGI_PASS_VALUE"
case "$FASTCGI_PASS" in
  alone) MODE="static"; FASTCGI_PASS="php:9900" ;;
  test)  FASTCGI_PASS="php:9900" ;;
  *:*)   ;;
  *)     FASTCGI_PASS="$FASTCGI_PASS:9900" ;;
esac

case "$MODE" in php|static) ;; *) echo "ERROR: MODE must be php or static (got '$MODE')" >&2; exit 1 ;; esac
case "$PHP_MODE" in classic|front) ;; *) echo "ERROR: PHP_MODE must be classic or front (got '$PHP_MODE')" >&2; exit 1 ;; esac
case "$HTTPS" in
  on|off) HTTPS_VALUE="$HTTPS" ;;
  auto)   HTTPS_VALUE='$forwarded_https' ;;
  *) echo "ERROR: HTTPS must be on, off or auto (got '$HTTPS')" >&2; exit 1 ;;
esac

# Script names must be plain file names ending with .php
valid_script() { printf '%s' "$1" | grep -Eq '^[A-Za-z0-9_-]+(\.[A-Za-z0-9_-]+)*\.php$'; }
escape_dots() { printf '%s' "$1" | sed 's/\./\\./g'; }

valid_script "$PHP_FRONT_SCRIPT" || { echo "ERROR: invalid PHP_FRONT_SCRIPT '$PHP_FRONT_SCRIPT'" >&2; exit 1; }
PHP_FRONT_SCRIPT_RE="$(escape_dots "$PHP_FRONT_SCRIPT")"

# Extra scripts reachable by URL in front mode (ex: a script switching the site to dev mode)
PHP_ALLOWED_CONF="# no extra PHP script allowed"
if [ -n "$PHP_ALLOWED_SCRIPTS" ]; then
  ALLOWED_RE=""
  OLD_IFS="$IFS"; IFS=','
  for script in $PHP_ALLOWED_SCRIPTS; do
    valid_script "$script" || { echo "ERROR: invalid script in PHP_ALLOWED_SCRIPTS: '$script'" >&2; exit 1; }
    ALLOWED_RE="${ALLOWED_RE:+$ALLOWED_RE|}$(escape_dots "$script")"
  done
  IFS="$OLD_IFS"
  ACCESS_RULES=""
  if [ -n "$PHP_ALLOWED_SCRIPTS_IPS" ]; then
    IFS=','
    for cidr in $PHP_ALLOWED_SCRIPTS_IPS; do ACCESS_RULES="${ACCESS_RULES}  allow ${cidr};
"; done
    IFS="$OLD_IFS"
    ACCESS_RULES="${ACCESS_RULES}  deny all;
"
  fi
  PHP_ALLOWED_CONF="location ~ ^/(?:${ALLOWED_RE})(?:/|\$) {
${ACCESS_RULES}  fastcgi_split_path_info ^(.+?\.php)(/.*)\$;
  try_files \$fastcgi_script_name =404;
  include ${NGINX_RUN_DIR}/snippets/fastcgi-php.conf;
}"
fi

case "$ERROR_LANG" in fr|en) ;; *) echo "ERROR: ERROR_LANG must be fr or en (got '$ERROR_LANG')" >&2; exit 1 ;; esac
case "$INTERCEPT_PHP_ERRORS" in on|off) FASTCGI_INTERCEPT="$INTERCEPT_PHP_ERRORS" ;; *) echo "ERROR: INTERCEPT_PHP_ERRORS must be on or off" >&2; exit 1 ;; esac

IS_ROOT=0
[ "$(id -u)" = "0" ] && IS_ROOT=1
if [ "$IS_ROOT" = "1" ]; then
  USER_DIRECTIVE="user www-data;"
else
  USER_DIRECTIVE="# running as UID $(id -u): user directive not used"
fi

# File descriptors: workers may raise their soft limit up to the hard limit of the container,
# and worker_connections must stay below it (otherwise nginx warns at start-up).
HARD_NOFILE="$(ulimit -Hn 2>/dev/null || echo 1024)"
case "$HARD_NOFILE" in unlimited|"") HARD_NOFILE=65536 ;; esac
[ "$HARD_NOFILE" -gt 16384 ] && HARD_NOFILE=16384
WORKER_RLIMIT_NOFILE="${WORKER_RLIMIT_NOFILE:-$HARD_NOFILE}"
if [ -z "${WORKER_CONNECTIONS:-}" ]; then
  WORKER_CONNECTIONS=$(( WORKER_RLIMIT_NOFILE / 2 ))
  [ "$WORKER_CONNECTIONS" -gt 4096 ] && WORKER_CONNECTIONS=4096
fi

[ "$ACCESS_LOG_ENABLED" = "1" ] && ACCESS_LOG="/dev/stdout" || ACCESS_LOG="off"

# DNS resolver (Docker embedded DNS in compose / swarm)
RESOLVER="$(awk '/^nameserver/ {print $2; exit}' /etc/resolv.conf 2>/dev/null || true)"
RESOLVER="${RESOLVER:-127.0.0.11}"

# Trusted proxies for the real client IP
REAL_IP_CONF="# real client IP: disabled"
if [ -n "$REAL_IP_FROM" ]; then
  REAL_IP_CONF=""
  OLD_IFS="$IFS"; IFS=','
  for cidr in $REAL_IP_FROM; do
    REAL_IP_CONF="${REAL_IP_CONF}set_real_ip_from ${cidr};
  "
  done
  IFS="$OLD_IFS"
  REAL_IP_CONF="${REAL_IP_CONF}real_ip_header X-Forwarded-For;
  real_ip_recursive on;"
fi

# Brotli (only when the module is installed in the image)
BROTLI_MODULE_CONF="# brotli: disabled"
BROTLI_CONF="# brotli: disabled"
if [ "$BROTLI" != "off" ] \
   && [ -f "$BROTLI_MODULE_DIR/ngx_http_brotli_filter_module.so" ] \
   && [ -f "$BROTLI_MODULE_DIR/ngx_http_brotli_static_module.so" ]; then
  BROTLI_MODULE_CONF="load_module $BROTLI_MODULE_DIR/ngx_http_brotli_filter_module.so;
load_module $BROTLI_MODULE_DIR/ngx_http_brotli_static_module.so;"
  BROTLI_CONF="brotli on;
  brotli_static on;
  brotli_comp_level 5;
  brotli_min_length 512;
  brotli_types text/plain text/css text/javascript application/javascript application/json
    application/ld+json text/xml application/xml application/atom+xml application/rss+xml
    image/svg+xml font/ttf font/otf application/vnd.ms-fontobject text/csv;"
elif [ "$BROTLI" = "on" ]; then
  echo "WARN: BROTLI=on but the brotli module is not installed in this image"
fi

export NGINX_RUN_DIR NGINX_CONF_DIR OVERRIDES_DIR WEBSITE_ROOT PUBLIC_DIR LISTEN_PORT \
  HTTPS_VALUE FASTCGI_PASS FASTCGI_READ_TIMEOUT CLIENT_MAX_BODY_SIZE CACHE_STATIC_MAX_AGE \
  CORS_ALLOW_ORIGIN X_FRAME_OPTIONS WORKER_PROCESSES ERROR_LOG_LEVEL ACCESS_LOG RESOLVER \
  USER_DIRECTIVE REAL_IP_CONF BROTLI_MODULE_CONF BROTLI_CONF WORKER_RLIMIT_NOFILE WORKER_CONNECTIONS \
  PHP_FRONT_SCRIPT PHP_FRONT_SCRIPT_RE PHP_ALLOWED_CONF FASTCGI_INTERCEPT

VARS='${NGINX_RUN_DIR} ${NGINX_CONF_DIR} ${OVERRIDES_DIR} ${WEBSITE_ROOT} ${PUBLIC_DIR}
${LISTEN_PORT} ${HTTPS_VALUE} ${FASTCGI_PASS} ${FASTCGI_READ_TIMEOUT} ${CLIENT_MAX_BODY_SIZE}
${CACHE_STATIC_MAX_AGE} ${CORS_ALLOW_ORIGIN} ${X_FRAME_OPTIONS} ${WORKER_PROCESSES}
${ERROR_LOG_LEVEL} ${ACCESS_LOG} ${RESOLVER} ${USER_DIRECTIVE} ${REAL_IP_CONF}
${BROTLI_MODULE_CONF} ${BROTLI_CONF} ${WORKER_RLIMIT_NOFILE} ${WORKER_CONNECTIONS}
${PHP_FRONT_SCRIPT} ${PHP_FRONT_SCRIPT_RE} ${PHP_ALLOWED_CONF} ${FASTCGI_INTERCEPT}'

# ---------- Render configuration ----------
# Override rule: /overrides/nginx.conf and /overrides/website.conf REPLACE the templates
# (copied as-is, no substitution). Drop-ins are ADDED: /overrides/conf.d/*.conf (http level)
# and /overrides/server.d/*.conf (inside the server block).
mkdir -p "$NGINX_RUN_DIR/sites" "$NGINX_RUN_DIR/snippets" \
  "$NGINX_RUN_DIR/tmp/client_body" "$NGINX_RUN_DIR/tmp/proxy" "$NGINX_RUN_DIR/tmp/fastcgi" \
  "$NGINX_RUN_DIR/tmp/uwsgi" "$NGINX_RUN_DIR/tmp/scgi"

render() { # render <template> <override-name> <destination>
  if [ -n "$2" ] && [ -f "$OVERRIDES_DIR/$2" ]; then
    echo "Config: using override $OVERRIDES_DIR/$2"
    cp "$OVERRIDES_DIR/$2" "$3"
  else
    envsubst "$VARS" < "$TEMPLATE_DIR/$1" > "$3"
  fi
}

for f in security-headers static-headers fastcgi-php; do
  envsubst "$VARS" < "$TEMPLATE_DIR/snippets/$f.conf" > "$NGINX_RUN_DIR/snippets/$f.conf"
done
envsubst "$VARS" < "$TEMPLATE_DIR/snippets/php-$PHP_MODE.conf" > "$NGINX_RUN_DIR/snippets/php-location.conf"

# ---------- Error pages ----------
# Pages for errors generated by nginx (403, 404 on static sites, 413, 502/503/504 when PHP is down...).
# Errors returned by the PHP application (Symfony 404/500 pages...) are left untouched unless
# INTERCEPT_PHP_ERRORS=on.
# Custom pages: /overrides/errors/<code>.html (raw), or /overrides/errors/error.html (generic template using
# ${ERROR_CODE}, ${ERROR_TITLE}, ${ERROR_MESSAGE}, ${ERROR_HOME_LABEL}). Other files of the directory
# (css, images, fonts) are served under /__errors/.
ERROR_CODES="400 401 403 404 405 408 413 414 429 500 501 502 503 504"
ERRORS_DIR="$NGINX_RUN_DIR/errors"
mkdir -p "$ERRORS_DIR"

error_text() { # error_text <code>: sets ERROR_TITLE and ERROR_MESSAGE
  case "$ERROR_LANG:$1" in
    fr:400) ERROR_TITLE="Requête incorrecte"; ERROR_MESSAGE="Le serveur n'a pas pu comprendre la requête." ;;
    fr:401) ERROR_TITLE="Authentification requise"; ERROR_MESSAGE="Vous devez vous identifier pour accéder à cette page." ;;
    fr:403) ERROR_TITLE="Accès refusé"; ERROR_MESSAGE="Vous n'avez pas l'autorisation d'accéder à cette page." ;;
    fr:404) ERROR_TITLE="Page introuvable"; ERROR_MESSAGE="La page demandée n'existe pas ou a été déplacée." ;;
    fr:405) ERROR_TITLE="Méthode non autorisée"; ERROR_MESSAGE="Cette action n'est pas autorisée sur cette page." ;;
    fr:408) ERROR_TITLE="Délai dépassé"; ERROR_MESSAGE="La requête a pris trop de temps. Veuillez réessayer." ;;
    fr:413) ERROR_TITLE="Fichier trop volumineux"; ERROR_MESSAGE="Les données envoyées dépassent la taille maximale autorisée." ;;
    fr:414) ERROR_TITLE="Adresse trop longue"; ERROR_MESSAGE="L'adresse demandée est trop longue." ;;
    fr:429) ERROR_TITLE="Trop de requêtes"; ERROR_MESSAGE="Veuillez patienter quelques instants avant de réessayer." ;;
    fr:500) ERROR_TITLE="Erreur interne"; ERROR_MESSAGE="Une erreur est survenue. Veuillez réessayer dans quelques instants." ;;
    fr:501) ERROR_TITLE="Fonction non disponible"; ERROR_MESSAGE="Le serveur ne sait pas traiter cette demande." ;;
    fr:502) ERROR_TITLE="Service indisponible"; ERROR_MESSAGE="Le site est momentanément inaccessible. Veuillez réessayer dans quelques instants." ;;
    fr:503) ERROR_TITLE="Service indisponible"; ERROR_MESSAGE="Le site est en maintenance ou surchargé. Veuillez réessayer dans quelques instants." ;;
    fr:504) ERROR_TITLE="Délai dépassé"; ERROR_MESSAGE="Le serveur met trop de temps à répondre. Veuillez réessayer dans quelques instants." ;;
    en:400) ERROR_TITLE="Bad request"; ERROR_MESSAGE="The server could not understand the request." ;;
    en:401) ERROR_TITLE="Authentication required"; ERROR_MESSAGE="You must sign in to access this page." ;;
    en:403) ERROR_TITLE="Access denied"; ERROR_MESSAGE="You do not have permission to access this page." ;;
    en:404) ERROR_TITLE="Page not found"; ERROR_MESSAGE="The requested page does not exist or has been moved." ;;
    en:405) ERROR_TITLE="Method not allowed"; ERROR_MESSAGE="This action is not allowed on this page." ;;
    en:408) ERROR_TITLE="Request timeout"; ERROR_MESSAGE="The request took too long. Please try again." ;;
    en:413) ERROR_TITLE="File too large"; ERROR_MESSAGE="The data you sent exceeds the maximum allowed size." ;;
    en:414) ERROR_TITLE="Address too long"; ERROR_MESSAGE="The requested address is too long." ;;
    en:429) ERROR_TITLE="Too many requests"; ERROR_MESSAGE="Please wait a moment before trying again." ;;
    en:500) ERROR_TITLE="Internal error"; ERROR_MESSAGE="Something went wrong. Please try again in a few moments." ;;
    en:501) ERROR_TITLE="Not implemented"; ERROR_MESSAGE="The server cannot handle this request." ;;
    en:502) ERROR_TITLE="Service unavailable"; ERROR_MESSAGE="The site is temporarily unreachable. Please try again in a few moments." ;;
    en:503) ERROR_TITLE="Service unavailable"; ERROR_MESSAGE="The site is under maintenance or overloaded. Please try again in a few moments." ;;
    en:504) ERROR_TITLE="Gateway timeout"; ERROR_MESSAGE="The server is taking too long to respond. Please try again in a few moments." ;;
  esac
}

ERROR_PAGE_CONF="# error pages: disabled"
if [ "$ERROR_PAGES" = "on" ]; then
  if [ -d "$OVERRIDES_DIR/errors" ]; then
    cp -R "$OVERRIDES_DIR/errors/." "$ERRORS_DIR/" 2>/dev/null || true
    rm -f "$ERRORS_DIR/error.html"
  fi
  GENERIC_TEMPLATE="$TEMPLATE_DIR/errors/default.html"
  [ -f "$OVERRIDES_DIR/errors/error.html" ] && GENERIC_TEMPLATE="$OVERRIDES_DIR/errors/error.html"
  [ "$ERROR_LANG" = "fr" ] && ERROR_HOME_LABEL="Retour à l'accueil" || ERROR_HOME_LABEL="Back to home"
  ERROR_PAGE_CONF="location ^~ /__errors/ {
  alias $ERRORS_DIR/;
  add_header Cache-Control \"no-cache\" always;
}"
  for code in $ERROR_CODES; do
    if [ ! -f "$OVERRIDES_DIR/errors/$code.html" ]; then
      ERROR_CODE="$code"; error_text "$code"
      export ERROR_LANG ERROR_CODE ERROR_TITLE ERROR_MESSAGE ERROR_HOME_LABEL
      envsubst '${ERROR_LANG} ${ERROR_CODE} ${ERROR_TITLE} ${ERROR_MESSAGE} ${ERROR_HOME_LABEL}' \
        < "$GENERIC_TEMPLATE" > "$ERRORS_DIR/$code.html"
    fi
    ERROR_PAGE_CONF="${ERROR_PAGE_CONF}
error_page $code /__errors/$code.html;"
  done
fi
printf '%s\n' "$ERROR_PAGE_CONF" > "$NGINX_RUN_DIR/snippets/error-pages.conf"

render nginx.conf nginx.conf "$NGINX_RUN_DIR/nginx.conf"

SITE_TEMPLATE="website.conf"
[ "$MODE" = "static" ] && SITE_TEMPLATE="website.alone"
if [ -f "$OVERRIDES_DIR/website.conf" ]; then
  render "$SITE_TEMPLATE" website.conf "$NGINX_RUN_DIR/sites/website.conf"
elif [ -f "$LEGACY_CUSTOM" ]; then
  echo "Config: using legacy custom config $LEGACY_CUSTOM"
  cp "$LEGACY_CUSTOM" "$NGINX_RUN_DIR/sites/website.conf"
else
  render "$SITE_TEMPLATE" "" "$NGINX_RUN_DIR/sites/website.conf"
fi

echo "Nginx: mode=${MODE} php_mode=${PHP_MODE} port=${LISTEN_PORT} public=${PUBLIC_DIR} UID=$(id -u)"
[ "$MODE" = "php" ] && echo "FastCGI: ${FASTCGI_PASS} | https=${HTTPS} | max body=${CLIENT_MAX_BODY_SIZE}"

# ---------- Validate before starting ----------
nginx -t -e /dev/stderr -c "$NGINX_RUN_DIR/nginx.conf"

# ---------- Main process ----------
# Any "nginx" command (default CMD, or a compose "command:") uses the rendered configuration.
if [ "${1:-}" = "nginx" ]; then
  shift
  case " $* " in
    *" -c "*) ;;
    *) set -- -c "$NGINX_RUN_DIR/nginx.conf" "$@" ;;
  esac
  case " $* " in
    *" daemon off"*) ;;
    *) set -- -g "daemon off;" "$@" ;;
  esac
  set -- nginx -e /dev/stderr "$@"
fi
exec "$@"
