include ${NGINX_CONF_DIR}/fastcgi.conf;
fastcgi_param PATH_INFO $fastcgi_path_info;
fastcgi_param HTTPS ${HTTPS_VALUE};
fastcgi_param APP_DEBUG "${APP_DEBUG}";
fastcgi_param APP_ENV "${APP_ENV}";

# Resolved at request time (see "resolver" in nginx.conf)
set $php_upstream "${FASTCGI_PASS}";
fastcgi_pass $php_upstream;

fastcgi_buffers 64 4K;
fastcgi_buffer_size 32k;
fastcgi_send_timeout ${FASTCGI_READ_TIMEOUT};
fastcgi_read_timeout ${FASTCGI_READ_TIMEOUT};
fastcgi_intercept_errors ${FASTCGI_INTERCEPT};
