# PHP_MODE=classic: any existing .php file can be executed (WordPress, legacy sites)
location ~ \.php(?:/|$) {
  fastcgi_split_path_info ^(.+?\.php)(/.*)$;
  try_files $fastcgi_script_name =404;
  include ${NGINX_RUN_DIR}/snippets/fastcgi-php.conf;
}
